# Generated by Django 2.2 on 2020-07-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Debug',
        ),
        migrations.RemoveField(
            model_name='friendlist',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friendlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='maillist',
            name='fromid',
        ),
        migrations.RemoveField(
            model_name='maillist',
            name='sendid',
        ),
        migrations.DeleteModel(
            name='Pool',
        ),
        migrations.DeleteModel(
            name='PoolHistory',
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['-level'], 'verbose_name': 'User Management', 'verbose_name_plural': 'User Management'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='betcoin',
            field=models.CharField(blank=True, default='[0,0,0,0,0,0,0,0,0]', max_length=128, null=True, verbose_name='Bet on gold coins'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='code',
            field=models.CharField(default='0000', max_length=30, verbose_name='Invitation code'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='coin',
            field=models.BigIntegerField(default=0, verbose_name='Number of gold coins'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='diamond',
            field=models.BigIntegerField(default=0, verbose_name='Number of diamonds'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='level',
            field=models.BigIntegerField(default=0, verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(blank=True, default='Rooster', max_length=30, null=True, verbose_name='nickname'),
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='MailList',
        ),
    ]
