# Generated by Django 2.2 on 2020-07-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20200718_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
